// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "InsertGuid.9d4397ae-2068-463f-84ac-0ca77c9ecf83";
        public const string Name = "Code Alignment";
        public const string Description = @"Made By HJO";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "재오 하";
        public const string Tags = "";
    }
}
