// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string InsertGuidString = "4355cf1a-98c6-4d2d-99a2-79721672e8dc";
        public static Guid InsertGuid = new Guid(InsertGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int TopLevelMenu = 0x1021;
        public const int MyCommand = 0x0100;
        public const int MyCommand2 = 0x0200;
        public const int MyCommand3 = 0x0300;
    }
}